package com.example

import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import java.io.File
import java.util.Locale

object ExportHelper {

    // Export sheet to CSV string
    fun exportToCSV(sheet: Sheet): String {
        var maxRow = 1
        var maxCol = 1
        
        for (coord in sheet.cells.keys) {
            val parsed = FormulaEvaluator.parseCoordinate(coord) ?: continue
            if (parsed.first > maxRow) maxRow = parsed.first
            if (parsed.second > maxCol) maxCol = parsed.second
        }

        val sb = java.lang.StringBuilder()
        for (r in 1..maxRow) {
            val rowValues = mutableListOf<String>()
            for (c in 1..maxCol) {
                val coord = "${FormulaEvaluator.getColName(c)}$r"
                val value = FormulaEvaluator.evaluateCell(coord, sheet)
                val escapedValue = if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
                    "\"" + value.replace("\"", "\"\"") + "\""
                } else {
                    value
                }
                rowValues.add(escapedValue)
            }
            sb.append(rowValues.joinToString(","))
            sb.append("\n")
        }
        return sb.toString()
    }

    // Import CSV string into a Sheet
    fun importFromCSV(csvContent: String, sheetName: String): Sheet {
        val cells = mutableMapOf<String, CellData>()
        val lines = csvContent.split("\n")
        
        var row = 1
        for (line in lines) {
            val trimmedLine = line.trim()
            if (trimmedLine.isEmpty()) continue
            
            val tokens = splitCSVLine(trimmedLine)
            for (col in tokens.indices) {
                val colLetter = FormulaEvaluator.getColName(col + 1)
                val coord = "$colLetter$row"
                val rawVal = tokens[col].trim()
                if (rawVal.isNotEmpty()) {
                    cells[coord] = CellData(value = rawVal)
                }
            }
            row++
        }
        return Sheet(name = sheetName, cells = cells)
    }

    private fun splitCSVLine(line: String): List<String> {
        val result = mutableListOf<String>()
        var inQuotes = false
        val currentToken = java.lang.StringBuilder()
        
        var i = 0
        while (i < line.length) {
            val c = line[i]
            if (c == '"') {
                if (inQuotes && i + 1 < line.length && line[i + 1] == '"') {
                    currentToken.append('"')
                    i++
                } else {
                    inQuotes = !inQuotes
                }
            } else if (c == ',' && !inQuotes) {
                result.add(currentToken.toString())
                currentToken.setLength(0)
            } else {
                currentToken.append(c)
            }
            i++
        }
        result.add(currentToken.toString())
        return result
    }

    // Generates a print-ready PDF file of the active sheet
    fun exportToPDF(sheet: Sheet, file: File, title: String = "SheetFlow Spreadsheet Report"): Boolean {
        return try {
            val pdfDoc = PdfDocument()
            val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
            val page = pdfDoc.startPage(pageInfo)
            
            val canvas = page.canvas
            val paint = Paint()
            
            // Draw Title
            paint.color = 0xFF0D9488.toInt()
            paint.textSize = 18f
            paint.isFakeBoldText = true
            canvas.drawText(title, 30f, 40f, paint)
            
            // Draw Subtitle / Developer credit
            paint.color = 0xFF555555.toInt()
            paint.textSize = 10f
            paint.isFakeBoldText = false
            canvas.drawText("Generated by SheetFlow — NexVora Lab's Ofc (Prince AR Abdur Rahman)", 30f, 58f, paint)
            
            var maxRow = 1
            var maxCol = 1
            for (coord in sheet.cells.keys) {
                val parsed = FormulaEvaluator.parseCoordinate(coord) ?: continue
                if (parsed.first > maxRow) maxRow = parsed.first
                if (parsed.second > maxCol) maxCol = parsed.second
            }
            
            val rowsToPrint = minOf(maxRow, 25)
            val colsToPrint = minOf(maxCol, 6)
            
            val startX = 30f
            val startY = 80f
            val colWidth = 80f
            val rowHeight = 24f
            
            // Table Header Background
            paint.color = 0xFFF0FDFA.toInt()
            canvas.drawRect(startX, startY, startX + (colsToPrint + 1) * colWidth, startY + rowHeight, paint)
            
            val gridPaint = Paint().apply {
                color = 0xFFCCCCCC.toInt()
                style = Paint.Style.STROKE
                strokeWidth = 0.5f
            }
            val textPaint = Paint().apply {
                color = 0xFF000000.toInt()
                textSize = 9f
                isAntiAlias = true
            }
            val boldTextPaint = Paint().apply {
                color = 0xFF000000.toInt()
                textSize = 9f
                isFakeBoldText = true
                isAntiAlias = true
            }
            
            // Draw headers
            boldTextPaint.color = 0xFF0D9488.toInt()
            canvas.drawText("No.", startX + 10f, startY + 16f, boldTextPaint)
            for (c in 1..colsToPrint) {
                canvas.drawText(FormulaEvaluator.getColName(c), startX + c * colWidth + 10f, startY + 16f, boldTextPaint)
            }
            
            // Draw grid
            for (r in 1..rowsToPrint) {
                val y = startY + r * rowHeight
                
                boldTextPaint.color = 0xFF555555.toInt()
                canvas.drawText(r.toString(), startX + 10f, y + 16f, boldTextPaint)
                
                for (c in 1..colsToPrint) {
                    val coord = "${FormulaEvaluator.getColName(c)}$r"
                    val evaluatedValue = FormulaEvaluator.evaluateCell(coord, sheet)
                    
                    val cell = sheet.cells[coord]
                    val drawPaint = if (cell?.bold == true) boldTextPaint else textPaint
                    drawPaint.color = if (cell?.textColor != null) cell.textColor.toInt() else 0xFF000000.toInt()
                    
                    if (cell?.backgroundColor != null && cell.backgroundColor != 0xFFFFFFFFL) {
                        val cellBgPaint = Paint().apply {
                            color = cell.backgroundColor.toInt()
                            style = Paint.Style.FILL
                        }
                        canvas.drawRect(
                            startX + c * colWidth,
                            y,
                            startX + (c + 1) * colWidth,
                            y + rowHeight,
                            cellBgPaint
                        )
                    }
                    
                    val displayText = if (evaluatedValue.length > 15) evaluatedValue.substring(0, 12) + "..." else evaluatedValue
                    canvas.drawText(displayText, startX + c * colWidth + 8f, y + 16f, drawPaint)
                }
            }
            
            for (r in 0..rowsToPrint) {
                val y = startY + r * rowHeight
                canvas.drawLine(startX, y, startX + (colsToPrint + 1) * colWidth, y, gridPaint)
            }
            canvas.drawLine(startX, startY + (rowsToPrint + 1) * rowHeight, startX + (colsToPrint + 1) * colWidth, startY + (rowsToPrint + 1) * rowHeight, gridPaint)
            
            for (c in 0..(colsToPrint + 1)) {
                val x = startX + c * colWidth
                canvas.drawLine(x, startY, x, startY + (rowsToPrint + 1) * rowHeight, gridPaint)
            }
            
            pdfDoc.finishPage(page)
            pdfDoc.writeTo(file.outputStream())
            pdfDoc.close()
            true
        } catch (e: Exception) {
            e.printStackTrace()
            false
        }
    }
}
